apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
## Define the config for the Service resource
spec:
  ## Define ports the service should serve on
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
  ## Define the Service type
  type: {{ .Values.service.type }}