apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
## Define the config for the Service resource
spec:
  ## Define ports the service should serve on
  ports:
  - port: 4111
    protocol: TCP
    targetPort: 3111
  selector:
    app: techtrends
  ## Define the Service type
  type: ClusterIP