apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
  name: techtrends-prod
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm
    repoURL: https://github.com/rithvik2607/nd064_course_1
    targetRevision: HEAD