# Automating the packaging for TechTrends using GitHub Actions

name: TechTrends - Package with Docker

# Trigger on every push to the main branch
on:
  push:
    branches: [ main ]

# jobs of the workflow run
job:
  # using a single job called build
  build:
    # the job will run on ubuntu
    runs-on: ubuntu-latest

    # steps of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./project/Dockerfile
          platforms: linux/amd64
          push: true
          tags: rithvik2607/techtrends:latest